vox:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    fwheel_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: f_wheel2base_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    bwheel_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: b_wheel2base_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    rwheel_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: r_wheel2base_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    lwheel_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: l_wheel2base_joint
        pid: {p: 1.0, i: 0.0, d: 0.0 }