vox:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    fwheel_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: f_wheel2base_joint
        pid: {p: 0.01, i: 0.0, d: 0.0}

    bwheel_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: b_wheel2base_joint
        pid: {p: 0.01, i: 0.0, d: 0.0}

    rwheel_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: r_wheel2base_joint
        pid: {p: 0.01, i: 0.0, d: 0.0}

    lwheel_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: l_wheel2base_joint
        pid: {p: 0.01, i: 0.0, d: 0.0 }